// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package com.encyclo.messages;

public final class CustomModels {
  private CustomModels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Entity extends
      com.google.protobuf.GeneratedMessage {
    // Use Entity.newBuilder() to construct.
    private Entity() {
      initFields();
    }
    private Entity(boolean noInit) {}
    
    private static final Entity defaultInstance;
    public static Entity getDefaultInstance() {
      return defaultInstance;
    }
    
    public Entity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.encyclo.messages.CustomModels.internal_static_encyclo_Entity_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.encyclo.messages.CustomModels.internal_static_encyclo_Entity_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional float rank = 2;
    public static final int RANK_FIELD_NUMBER = 2;
    private boolean hasRank;
    private float rank_ = 0F;
    public boolean hasRank() { return hasRank; }
    public float getRank() { return rank_; }
    
    // optional int32 parent_id = 3;
    public static final int PARENT_ID_FIELD_NUMBER = 3;
    private boolean hasParentId;
    private int parentId_ = 0;
    public boolean hasParentId() { return hasParentId; }
    public int getParentId() { return parentId_; }
    
    // optional int32 component_id = 4;
    public static final int COMPONENT_ID_FIELD_NUMBER = 4;
    private boolean hasComponentId;
    private int componentId_ = 0;
    public boolean hasComponentId() { return hasComponentId; }
    public int getComponentId() { return componentId_; }
    
    // optional int32 user_id = 5;
    public static final int USER_ID_FIELD_NUMBER = 5;
    private boolean hasUserId;
    private int userId_ = 0;
    public boolean hasUserId() { return hasUserId; }
    public int getUserId() { return userId_; }
    
    // repeated .encyclo.Document documents = 6;
    public static final int DOCUMENTS_FIELD_NUMBER = 6;
    private java.util.List<com.encyclo.messages.CustomModels.Document> documents_ =
      java.util.Collections.emptyList();
    public java.util.List<com.encyclo.messages.CustomModels.Document> getDocumentsList() {
      return documents_;
    }
    public int getDocumentsCount() { return documents_.size(); }
    public com.encyclo.messages.CustomModels.Document getDocuments(int index) {
      return documents_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasRank()) {
        output.writeFloat(2, getRank());
      }
      if (hasParentId()) {
        output.writeInt32(3, getParentId());
      }
      if (hasComponentId()) {
        output.writeInt32(4, getComponentId());
      }
      if (hasUserId()) {
        output.writeInt32(5, getUserId());
      }
      for (com.encyclo.messages.CustomModels.Document element : getDocumentsList()) {
        output.writeMessage(6, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasRank()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, getRank());
      }
      if (hasParentId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getParentId());
      }
      if (hasComponentId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getComponentId());
      }
      if (hasUserId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getUserId());
      }
      for (com.encyclo.messages.CustomModels.Document element : getDocumentsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.encyclo.messages.CustomModels.Entity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Entity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Entity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Entity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Entity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Entity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Entity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.CustomModels.Entity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.CustomModels.Entity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Entity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.encyclo.messages.CustomModels.Entity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.encyclo.messages.CustomModels.Entity result;
      
      // Construct using com.encyclo.messages.CustomModels.Entity.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.encyclo.messages.CustomModels.Entity();
        return builder;
      }
      
      protected com.encyclo.messages.CustomModels.Entity internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.encyclo.messages.CustomModels.Entity();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.encyclo.messages.CustomModels.Entity.getDescriptor();
      }
      
      public com.encyclo.messages.CustomModels.Entity getDefaultInstanceForType() {
        return com.encyclo.messages.CustomModels.Entity.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.encyclo.messages.CustomModels.Entity build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.encyclo.messages.CustomModels.Entity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.encyclo.messages.CustomModels.Entity buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.documents_ != java.util.Collections.EMPTY_LIST) {
          result.documents_ =
            java.util.Collections.unmodifiableList(result.documents_);
        }
        com.encyclo.messages.CustomModels.Entity returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.encyclo.messages.CustomModels.Entity) {
          return mergeFrom((com.encyclo.messages.CustomModels.Entity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.encyclo.messages.CustomModels.Entity other) {
        if (other == com.encyclo.messages.CustomModels.Entity.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (other.hasParentId()) {
          setParentId(other.getParentId());
        }
        if (other.hasComponentId()) {
          setComponentId(other.getComponentId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (!other.documents_.isEmpty()) {
          if (result.documents_.isEmpty()) {
            result.documents_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Document>();
          }
          result.documents_.addAll(other.documents_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 21: {
              setRank(input.readFloat());
              break;
            }
            case 24: {
              setParentId(input.readInt32());
              break;
            }
            case 32: {
              setComponentId(input.readInt32());
              break;
            }
            case 40: {
              setUserId(input.readInt32());
              break;
            }
            case 50: {
              com.encyclo.messages.CustomModels.Document.Builder subBuilder = com.encyclo.messages.CustomModels.Document.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDocuments(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional float rank = 2;
      public boolean hasRank() {
        return result.hasRank();
      }
      public float getRank() {
        return result.getRank();
      }
      public Builder setRank(float value) {
        result.hasRank = true;
        result.rank_ = value;
        return this;
      }
      public Builder clearRank() {
        result.hasRank = false;
        result.rank_ = 0F;
        return this;
      }
      
      // optional int32 parent_id = 3;
      public boolean hasParentId() {
        return result.hasParentId();
      }
      public int getParentId() {
        return result.getParentId();
      }
      public Builder setParentId(int value) {
        result.hasParentId = true;
        result.parentId_ = value;
        return this;
      }
      public Builder clearParentId() {
        result.hasParentId = false;
        result.parentId_ = 0;
        return this;
      }
      
      // optional int32 component_id = 4;
      public boolean hasComponentId() {
        return result.hasComponentId();
      }
      public int getComponentId() {
        return result.getComponentId();
      }
      public Builder setComponentId(int value) {
        result.hasComponentId = true;
        result.componentId_ = value;
        return this;
      }
      public Builder clearComponentId() {
        result.hasComponentId = false;
        result.componentId_ = 0;
        return this;
      }
      
      // optional int32 user_id = 5;
      public boolean hasUserId() {
        return result.hasUserId();
      }
      public int getUserId() {
        return result.getUserId();
      }
      public Builder setUserId(int value) {
        result.hasUserId = true;
        result.userId_ = value;
        return this;
      }
      public Builder clearUserId() {
        result.hasUserId = false;
        result.userId_ = 0;
        return this;
      }
      
      // repeated .encyclo.Document documents = 6;
      public java.util.List<com.encyclo.messages.CustomModels.Document> getDocumentsList() {
        return java.util.Collections.unmodifiableList(result.documents_);
      }
      public int getDocumentsCount() {
        return result.getDocumentsCount();
      }
      public com.encyclo.messages.CustomModels.Document getDocuments(int index) {
        return result.getDocuments(index);
      }
      public Builder setDocuments(int index, com.encyclo.messages.CustomModels.Document value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.documents_.set(index, value);
        return this;
      }
      public Builder setDocuments(int index, com.encyclo.messages.CustomModels.Document.Builder builderForValue) {
        result.documents_.set(index, builderForValue.build());
        return this;
      }
      public Builder addDocuments(com.encyclo.messages.CustomModels.Document value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.documents_.isEmpty()) {
          result.documents_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Document>();
        }
        result.documents_.add(value);
        return this;
      }
      public Builder addDocuments(com.encyclo.messages.CustomModels.Document.Builder builderForValue) {
        if (result.documents_.isEmpty()) {
          result.documents_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Document>();
        }
        result.documents_.add(builderForValue.build());
        return this;
      }
      public Builder addAllDocuments(
          java.lang.Iterable<? extends com.encyclo.messages.CustomModels.Document> values) {
        if (result.documents_.isEmpty()) {
          result.documents_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Document>();
        }
        super.addAll(values, result.documents_);
        return this;
      }
      public Builder clearDocuments() {
        result.documents_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:encyclo.Entity)
    }
    
    static {
      defaultInstance = new Entity(true);
      com.encyclo.messages.CustomModels.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:encyclo.Entity)
  }
  
  public static final class Document extends
      com.google.protobuf.GeneratedMessage {
    // Use Document.newBuilder() to construct.
    private Document() {
      initFields();
    }
    private Document(boolean noInit) {}
    
    private static final Document defaultInstance;
    public static Document getDefaultInstance() {
      return defaultInstance;
    }
    
    public Document getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.encyclo.messages.CustomModels.internal_static_encyclo_Document_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.encyclo.messages.CustomModels.internal_static_encyclo_Document_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // repeated .encyclo.Entity entities = 2;
    public static final int ENTITIES_FIELD_NUMBER = 2;
    private java.util.List<com.encyclo.messages.CustomModels.Entity> entities_ =
      java.util.Collections.emptyList();
    public java.util.List<com.encyclo.messages.CustomModels.Entity> getEntitiesList() {
      return entities_;
    }
    public int getEntitiesCount() { return entities_.size(); }
    public com.encyclo.messages.CustomModels.Entity getEntities(int index) {
      return entities_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      for (com.encyclo.messages.CustomModels.Entity element : getEntitiesList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      for (com.encyclo.messages.CustomModels.Entity element : getEntitiesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.encyclo.messages.CustomModels.Document parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Document parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Document parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Document parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Document parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Document parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Document parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.CustomModels.Document parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.CustomModels.Document parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.CustomModels.Document parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.encyclo.messages.CustomModels.Document prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.encyclo.messages.CustomModels.Document result;
      
      // Construct using com.encyclo.messages.CustomModels.Document.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.encyclo.messages.CustomModels.Document();
        return builder;
      }
      
      protected com.encyclo.messages.CustomModels.Document internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.encyclo.messages.CustomModels.Document();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.encyclo.messages.CustomModels.Document.getDescriptor();
      }
      
      public com.encyclo.messages.CustomModels.Document getDefaultInstanceForType() {
        return com.encyclo.messages.CustomModels.Document.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.encyclo.messages.CustomModels.Document build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.encyclo.messages.CustomModels.Document buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.encyclo.messages.CustomModels.Document buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.entities_ != java.util.Collections.EMPTY_LIST) {
          result.entities_ =
            java.util.Collections.unmodifiableList(result.entities_);
        }
        com.encyclo.messages.CustomModels.Document returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.encyclo.messages.CustomModels.Document) {
          return mergeFrom((com.encyclo.messages.CustomModels.Document)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.encyclo.messages.CustomModels.Document other) {
        if (other == com.encyclo.messages.CustomModels.Document.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.entities_.isEmpty()) {
          if (result.entities_.isEmpty()) {
            result.entities_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Entity>();
          }
          result.entities_.addAll(other.entities_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              com.encyclo.messages.CustomModels.Entity.Builder subBuilder = com.encyclo.messages.CustomModels.Entity.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntities(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // repeated .encyclo.Entity entities = 2;
      public java.util.List<com.encyclo.messages.CustomModels.Entity> getEntitiesList() {
        return java.util.Collections.unmodifiableList(result.entities_);
      }
      public int getEntitiesCount() {
        return result.getEntitiesCount();
      }
      public com.encyclo.messages.CustomModels.Entity getEntities(int index) {
        return result.getEntities(index);
      }
      public Builder setEntities(int index, com.encyclo.messages.CustomModels.Entity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.entities_.set(index, value);
        return this;
      }
      public Builder setEntities(int index, com.encyclo.messages.CustomModels.Entity.Builder builderForValue) {
        result.entities_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEntities(com.encyclo.messages.CustomModels.Entity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.entities_.isEmpty()) {
          result.entities_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Entity>();
        }
        result.entities_.add(value);
        return this;
      }
      public Builder addEntities(com.encyclo.messages.CustomModels.Entity.Builder builderForValue) {
        if (result.entities_.isEmpty()) {
          result.entities_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Entity>();
        }
        result.entities_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEntities(
          java.lang.Iterable<? extends com.encyclo.messages.CustomModels.Entity> values) {
        if (result.entities_.isEmpty()) {
          result.entities_ = new java.util.ArrayList<com.encyclo.messages.CustomModels.Entity>();
        }
        super.addAll(values, result.entities_);
        return this;
      }
      public Builder clearEntities() {
        result.entities_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:encyclo.Document)
    }
    
    static {
      defaultInstance = new Document(true);
      com.encyclo.messages.CustomModels.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:encyclo.Document)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_encyclo_Entity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_encyclo_Entity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_encyclo_Document_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_encyclo_Document_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014models.proto\022\007encyclo\"\202\001\n\006Entity\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004rank\030\002 \001(\002\022\021\n\tparent_id\030\003 \001(\005\022" +
      "\024\n\014component_id\030\004 \001(\005\022\017\n\007user_id\030\005 \001(\005\022$" +
      "\n\tdocuments\030\006 \003(\0132\021.encyclo.Document\"9\n\010" +
      "Document\022\n\n\002id\030\001 \001(\005\022!\n\010entities\030\002 \003(\0132\017" +
      ".encyclo.EntityB$\n\024com.encyclo.messagesB" +
      "\014CustomModels"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_encyclo_Entity_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_encyclo_Entity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_encyclo_Entity_descriptor,
              new java.lang.String[] { "Id", "Rank", "ParentId", "ComponentId", "UserId", "Documents", },
              com.encyclo.messages.CustomModels.Entity.class,
              com.encyclo.messages.CustomModels.Entity.Builder.class);
          internal_static_encyclo_Document_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_encyclo_Document_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_encyclo_Document_descriptor,
              new java.lang.String[] { "Id", "Entities", },
              com.encyclo.messages.CustomModels.Document.class,
              com.encyclo.messages.CustomModels.Document.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
