// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.encyclo.messages;

public final class Search {
  private Search() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SearchQuery extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchQuery.newBuilder() to construct.
    private SearchQuery() {
      initFields();
    }
    private SearchQuery(boolean noInit) {}
    
    private static final SearchQuery defaultInstance;
    public static SearchQuery getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchQuery getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.encyclo.messages.Search.internal_static_encyclo_SearchQuery_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.encyclo.messages.Search.internal_static_encyclo_SearchQuery_fieldAccessorTable;
    }
    
    public static final class WhereStatement extends
        com.google.protobuf.GeneratedMessage {
      // Use WhereStatement.newBuilder() to construct.
      private WhereStatement() {
        initFields();
      }
      private WhereStatement(boolean noInit) {}
      
      private static final WhereStatement defaultInstance;
      public static WhereStatement getDefaultInstance() {
        return defaultInstance;
      }
      
      public WhereStatement getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.encyclo.messages.Search.internal_static_encyclo_SearchQuery_WhereStatement_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.encyclo.messages.Search.internal_static_encyclo_SearchQuery_WhereStatement_fieldAccessorTable;
      }
      
      public enum Operator
          implements com.google.protobuf.ProtocolMessageEnum {
        EQUALS(0, 0),
        GREATER(1, 1),
        SMALLER(2, 2),
        GREATER_OR_EQUALS(3, 3),
        SMALLER_OR_EQUALS(4, 4),
        NOT_EQUALS(5, 5),
        IS_NULL(6, 6),
        IS_NOT_NULL(7, 7),
        ;
        
        
        public final int getNumber() { return value; }
        
        public static Operator valueOf(int value) {
          switch (value) {
            case 0: return EQUALS;
            case 1: return GREATER;
            case 2: return SMALLER;
            case 3: return GREATER_OR_EQUALS;
            case 4: return SMALLER_OR_EQUALS;
            case 5: return NOT_EQUALS;
            case 6: return IS_NULL;
            case 7: return IS_NOT_NULL;
            default: return null;
          }
        }
        
        public static com.google.protobuf.Internal.EnumLiteMap<Operator>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<Operator>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Operator>() {
                public Operator findValueByNumber(int number) {
                  return Operator.valueOf(number)
        ;        }
              };
        
        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return com.encyclo.messages.Search.SearchQuery.WhereStatement.getDescriptor().getEnumTypes().get(0);
        }
        
        private static final Operator[] VALUES = {
          EQUALS, GREATER, SMALLER, GREATER_OR_EQUALS, SMALLER_OR_EQUALS, NOT_EQUALS, IS_NULL, IS_NOT_NULL, 
        };
        public static Operator valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }
        private final int index;
        private final int value;
        private Operator(int index, int value) {
          this.index = index;
          this.value = value;
        }
        
        static {
          com.encyclo.messages.Search.getDescriptor();
        }
        
        // @@protoc_insertion_point(enum_scope:encyclo.SearchQuery.WhereStatement.Operator)
      }
      
      public static final class LogicalStatement extends
          com.google.protobuf.GeneratedMessage {
        // Use LogicalStatement.newBuilder() to construct.
        private LogicalStatement() {
          initFields();
        }
        private LogicalStatement(boolean noInit) {}
        
        private static final LogicalStatement defaultInstance;
        public static LogicalStatement getDefaultInstance() {
          return defaultInstance;
        }
        
        public LogicalStatement getDefaultInstanceForType() {
          return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.encyclo.messages.Search.internal_static_encyclo_SearchQuery_WhereStatement_LogicalStatement_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.encyclo.messages.Search.internal_static_encyclo_SearchQuery_WhereStatement_LogicalStatement_fieldAccessorTable;
        }
        
        public enum LogicalStatementType
            implements com.google.protobuf.ProtocolMessageEnum {
          OR(0, 0),
          AND(1, 1),
          XOR(2, 2),
          ;
          
          
          public final int getNumber() { return value; }
          
          public static LogicalStatementType valueOf(int value) {
            switch (value) {
              case 0: return OR;
              case 1: return AND;
              case 2: return XOR;
              default: return null;
            }
          }
          
          public static com.google.protobuf.Internal.EnumLiteMap<LogicalStatementType>
              internalGetValueMap() {
            return internalValueMap;
          }
          private static com.google.protobuf.Internal.EnumLiteMap<LogicalStatementType>
              internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<LogicalStatementType>() {
                  public LogicalStatementType findValueByNumber(int number) {
                    return LogicalStatementType.valueOf(number)
          ;        }
                };
          
          public final com.google.protobuf.Descriptors.EnumValueDescriptor
              getValueDescriptor() {
            return getDescriptor().getValues().get(index);
          }
          public final com.google.protobuf.Descriptors.EnumDescriptor
              getDescriptorForType() {
            return getDescriptor();
          }
          public static final com.google.protobuf.Descriptors.EnumDescriptor
              getDescriptor() {
            return com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.getDescriptor().getEnumTypes().get(0);
          }
          
          private static final LogicalStatementType[] VALUES = {
            OR, AND, XOR, 
          };
          public static LogicalStatementType valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
              throw new java.lang.IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
          }
          private final int index;
          private final int value;
          private LogicalStatementType(int index, int value) {
            this.index = index;
            this.value = value;
          }
          
          static {
            com.encyclo.messages.Search.getDescriptor();
          }
          
          // @@protoc_insertion_point(enum_scope:encyclo.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType)
        }
        
        // optional .encyclo.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType logical_type = 1;
        public static final int LOGICAL_TYPE_FIELD_NUMBER = 1;
        private boolean hasLogicalType;
        private com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType logicalType_;
        public boolean hasLogicalType() { return hasLogicalType; }
        public com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType getLogicalType() { return logicalType_; }
        
        // optional .encyclo.SearchQuery.WhereStatement where_statement = 2;
        public static final int WHERE_STATEMENT_FIELD_NUMBER = 2;
        private boolean hasWhereStatement;
        private com.encyclo.messages.Search.SearchQuery.WhereStatement whereStatement_;
        public boolean hasWhereStatement() { return hasWhereStatement; }
        public com.encyclo.messages.Search.SearchQuery.WhereStatement getWhereStatement() { return whereStatement_; }
        
        private void initFields() {
          logicalType_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType.OR;
          whereStatement_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance();
        }
        public final boolean isInitialized() {
          return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (hasLogicalType()) {
            output.writeEnum(1, getLogicalType().getNumber());
          }
          if (hasWhereStatement()) {
            output.writeMessage(2, getWhereStatement());
          }
          getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
        
          size = 0;
          if (hasLogicalType()) {
            size += com.google.protobuf.CodedOutputStream
              .computeEnumSize(1, getLogicalType().getNumber());
          }
          if (hasWhereStatement()) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(2, getWhereStatement());
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }
        
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        
        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }
        
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> {
          private com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement result;
          
          // Construct using com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.newBuilder()
          private Builder() {}
          
          private static Builder create() {
            Builder builder = new Builder();
            builder.result = new com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement();
            return builder;
          }
          
          protected com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement internalGetResult() {
            return result;
          }
          
          public Builder clear() {
            if (result == null) {
              throw new IllegalStateException(
                "Cannot call clear() after build().");
            }
            result = new com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement();
            return this;
          }
          
          public Builder clone() {
            return create().mergeFrom(result);
          }
          
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.getDescriptor();
          }
          
          public com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement getDefaultInstanceForType() {
            return com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.getDefaultInstance();
          }
          
          public boolean isInitialized() {
            return result.isInitialized();
          }
          public com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement build() {
            if (result != null && !isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return buildPartial();
          }
          
          private com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement buildParsed()
              throws com.google.protobuf.InvalidProtocolBufferException {
            if (!isInitialized()) {
              throw newUninitializedMessageException(
                result).asInvalidProtocolBufferException();
            }
            return buildPartial();
          }
          
          public com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement buildPartial() {
            if (result == null) {
              throw new IllegalStateException(
                "build() has already been called on this Builder.");
            }
            com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement returnMe = result;
            result = null;
            return returnMe;
          }
          
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement) {
              return mergeFrom((com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }
          
          public Builder mergeFrom(com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement other) {
            if (other == com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.getDefaultInstance()) return this;
            if (other.hasLogicalType()) {
              setLogicalType(other.getLogicalType());
            }
            if (other.hasWhereStatement()) {
              mergeWhereStatement(other.getWhereStatement());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }
          
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder(
                this.getUnknownFields());
            while (true) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  this.setUnknownFields(unknownFields.build());
                  return this;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    this.setUnknownFields(unknownFields.build());
                    return this;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();
                  com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType value = com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType.valueOf(rawValue);
                  if (value == null) {
                    unknownFields.mergeVarintField(1, rawValue);
                  } else {
                    setLogicalType(value);
                  }
                  break;
                }
                case 18: {
                  com.encyclo.messages.Search.SearchQuery.WhereStatement.Builder subBuilder = com.encyclo.messages.Search.SearchQuery.WhereStatement.newBuilder();
                  if (hasWhereStatement()) {
                    subBuilder.mergeFrom(getWhereStatement());
                  }
                  input.readMessage(subBuilder, extensionRegistry);
                  setWhereStatement(subBuilder.buildPartial());
                  break;
                }
              }
            }
          }
          
          
          // optional .encyclo.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType logical_type = 1;
          public boolean hasLogicalType() {
            return result.hasLogicalType();
          }
          public com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType getLogicalType() {
            return result.getLogicalType();
          }
          public Builder setLogicalType(com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType value) {
            if (value == null) {
              throw new NullPointerException();
            }
            result.hasLogicalType = true;
            result.logicalType_ = value;
            return this;
          }
          public Builder clearLogicalType() {
            result.hasLogicalType = false;
            result.logicalType_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.LogicalStatementType.OR;
            return this;
          }
          
          // optional .encyclo.SearchQuery.WhereStatement where_statement = 2;
          public boolean hasWhereStatement() {
            return result.hasWhereStatement();
          }
          public com.encyclo.messages.Search.SearchQuery.WhereStatement getWhereStatement() {
            return result.getWhereStatement();
          }
          public Builder setWhereStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement value) {
            if (value == null) {
              throw new NullPointerException();
            }
            result.hasWhereStatement = true;
            result.whereStatement_ = value;
            return this;
          }
          public Builder setWhereStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement.Builder builderForValue) {
            result.hasWhereStatement = true;
            result.whereStatement_ = builderForValue.build();
            return this;
          }
          public Builder mergeWhereStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement value) {
            if (result.hasWhereStatement() &&
                result.whereStatement_ != com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance()) {
              result.whereStatement_ =
                com.encyclo.messages.Search.SearchQuery.WhereStatement.newBuilder(result.whereStatement_).mergeFrom(value).buildPartial();
            } else {
              result.whereStatement_ = value;
            }
            result.hasWhereStatement = true;
            return this;
          }
          public Builder clearWhereStatement() {
            result.hasWhereStatement = false;
            result.whereStatement_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance();
            return this;
          }
          
          // @@protoc_insertion_point(builder_scope:encyclo.SearchQuery.WhereStatement.LogicalStatement)
        }
        
        static {
          defaultInstance = new LogicalStatement(true);
          com.encyclo.messages.Search.internalForceInit();
          defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:encyclo.SearchQuery.WhereStatement.LogicalStatement)
      }
      
      // optional int32 field = 1;
      public static final int FIELD_FIELD_NUMBER = 1;
      private boolean hasField;
      private int field_ = 0;
      public boolean hasField() { return hasField; }
      public int getField() { return field_; }
      
      // optional .encyclo.SearchQuery.WhereStatement.Operator operator = 2;
      public static final int OPERATOR_FIELD_NUMBER = 2;
      private boolean hasOperator;
      private com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator operator_;
      public boolean hasOperator() { return hasOperator; }
      public com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator getOperator() { return operator_; }
      
      // optional string value = 3;
      public static final int VALUE_FIELD_NUMBER = 3;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      // repeated .encyclo.SearchQuery.WhereStatement.LogicalStatement additional_statement = 4;
      public static final int ADDITIONAL_STATEMENT_FIELD_NUMBER = 4;
      private java.util.List<com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement> additionalStatement_ =
        java.util.Collections.emptyList();
      public java.util.List<com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement> getAdditionalStatementList() {
        return additionalStatement_;
      }
      public int getAdditionalStatementCount() { return additionalStatement_.size(); }
      public com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement getAdditionalStatement(int index) {
        return additionalStatement_.get(index);
      }
      
      private void initFields() {
        operator_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator.EQUALS;
      }
      public final boolean isInitialized() {
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasField()) {
          output.writeInt32(1, getField());
        }
        if (hasOperator()) {
          output.writeEnum(2, getOperator().getNumber());
        }
        if (hasValue()) {
          output.writeString(3, getValue());
        }
        for (com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement element : getAdditionalStatementList()) {
          output.writeMessage(4, element);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasField()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getField());
        }
        if (hasOperator()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, getOperator().getNumber());
        }
        if (hasValue()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getValue());
        }
        for (com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement element : getAdditionalStatementList()) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, element);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.encyclo.messages.Search.SearchQuery.WhereStatement parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.encyclo.messages.Search.SearchQuery.WhereStatement prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.encyclo.messages.Search.SearchQuery.WhereStatement result;
        
        // Construct using com.encyclo.messages.Search.SearchQuery.WhereStatement.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.encyclo.messages.Search.SearchQuery.WhereStatement();
          return builder;
        }
        
        protected com.encyclo.messages.Search.SearchQuery.WhereStatement internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.encyclo.messages.Search.SearchQuery.WhereStatement();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.encyclo.messages.Search.SearchQuery.WhereStatement.getDescriptor();
        }
        
        public com.encyclo.messages.Search.SearchQuery.WhereStatement getDefaultInstanceForType() {
          return com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.encyclo.messages.Search.SearchQuery.WhereStatement build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.encyclo.messages.Search.SearchQuery.WhereStatement buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.encyclo.messages.Search.SearchQuery.WhereStatement buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          if (result.additionalStatement_ != java.util.Collections.EMPTY_LIST) {
            result.additionalStatement_ =
              java.util.Collections.unmodifiableList(result.additionalStatement_);
          }
          com.encyclo.messages.Search.SearchQuery.WhereStatement returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.encyclo.messages.Search.SearchQuery.WhereStatement) {
            return mergeFrom((com.encyclo.messages.Search.SearchQuery.WhereStatement)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.encyclo.messages.Search.SearchQuery.WhereStatement other) {
          if (other == com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance()) return this;
          if (other.hasField()) {
            setField(other.getField());
          }
          if (other.hasOperator()) {
            setOperator(other.getOperator());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          if (!other.additionalStatement_.isEmpty()) {
            if (result.additionalStatement_.isEmpty()) {
              result.additionalStatement_ = new java.util.ArrayList<com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement>();
            }
            result.additionalStatement_.addAll(other.additionalStatement_);
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setField(input.readInt32());
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator value = com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  setOperator(value);
                }
                break;
              }
              case 26: {
                setValue(input.readString());
                break;
              }
              case 34: {
                com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.Builder subBuilder = com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addAdditionalStatement(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        
        // optional int32 field = 1;
        public boolean hasField() {
          return result.hasField();
        }
        public int getField() {
          return result.getField();
        }
        public Builder setField(int value) {
          result.hasField = true;
          result.field_ = value;
          return this;
        }
        public Builder clearField() {
          result.hasField = false;
          result.field_ = 0;
          return this;
        }
        
        // optional .encyclo.SearchQuery.WhereStatement.Operator operator = 2;
        public boolean hasOperator() {
          return result.hasOperator();
        }
        public com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator getOperator() {
          return result.getOperator();
        }
        public Builder setOperator(com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasOperator = true;
          result.operator_ = value;
          return this;
        }
        public Builder clearOperator() {
          result.hasOperator = false;
          result.operator_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.Operator.EQUALS;
          return this;
        }
        
        // optional string value = 3;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = getDefaultInstance().getValue();
          return this;
        }
        
        // repeated .encyclo.SearchQuery.WhereStatement.LogicalStatement additional_statement = 4;
        public java.util.List<com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement> getAdditionalStatementList() {
          return java.util.Collections.unmodifiableList(result.additionalStatement_);
        }
        public int getAdditionalStatementCount() {
          return result.getAdditionalStatementCount();
        }
        public com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement getAdditionalStatement(int index) {
          return result.getAdditionalStatement(index);
        }
        public Builder setAdditionalStatement(int index, com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.additionalStatement_.set(index, value);
          return this;
        }
        public Builder setAdditionalStatement(int index, com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.Builder builderForValue) {
          result.additionalStatement_.set(index, builderForValue.build());
          return this;
        }
        public Builder addAdditionalStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement value) {
          if (value == null) {
            throw new NullPointerException();
          }
          if (result.additionalStatement_.isEmpty()) {
            result.additionalStatement_ = new java.util.ArrayList<com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement>();
          }
          result.additionalStatement_.add(value);
          return this;
        }
        public Builder addAdditionalStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.Builder builderForValue) {
          if (result.additionalStatement_.isEmpty()) {
            result.additionalStatement_ = new java.util.ArrayList<com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement>();
          }
          result.additionalStatement_.add(builderForValue.build());
          return this;
        }
        public Builder addAllAdditionalStatement(
            java.lang.Iterable<? extends com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement> values) {
          if (result.additionalStatement_.isEmpty()) {
            result.additionalStatement_ = new java.util.ArrayList<com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement>();
          }
          super.addAll(values, result.additionalStatement_);
          return this;
        }
        public Builder clearAdditionalStatement() {
          result.additionalStatement_ = java.util.Collections.emptyList();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:encyclo.SearchQuery.WhereStatement)
      }
      
      static {
        defaultInstance = new WhereStatement(true);
        com.encyclo.messages.Search.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:encyclo.SearchQuery.WhereStatement)
    }
    
    // optional string index_name = 1;
    public static final int INDEX_NAME_FIELD_NUMBER = 1;
    private boolean hasIndexName;
    private java.lang.String indexName_ = "";
    public boolean hasIndexName() { return hasIndexName; }
    public java.lang.String getIndexName() { return indexName_; }
    
    // optional string table_name = 2;
    public static final int TABLE_NAME_FIELD_NUMBER = 2;
    private boolean hasTableName;
    private java.lang.String tableName_ = "";
    public boolean hasTableName() { return hasTableName; }
    public java.lang.String getTableName() { return tableName_; }
    
    // repeated int32 select_field = 3;
    public static final int SELECT_FIELD_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> selectField_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getSelectFieldList() {
      return selectField_;
    }
    public int getSelectFieldCount() { return selectField_.size(); }
    public int getSelectField(int index) {
      return selectField_.get(index);
    }
    
    // optional .encyclo.SearchQuery.WhereStatement where_statement = 4;
    public static final int WHERE_STATEMENT_FIELD_NUMBER = 4;
    private boolean hasWhereStatement;
    private com.encyclo.messages.Search.SearchQuery.WhereStatement whereStatement_;
    public boolean hasWhereStatement() { return hasWhereStatement; }
    public com.encyclo.messages.Search.SearchQuery.WhereStatement getWhereStatement() { return whereStatement_; }
    
    private void initFields() {
      whereStatement_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasIndexName()) {
        output.writeString(1, getIndexName());
      }
      if (hasTableName()) {
        output.writeString(2, getTableName());
      }
      for (int element : getSelectFieldList()) {
        output.writeInt32(3, element);
      }
      if (hasWhereStatement()) {
        output.writeMessage(4, getWhereStatement());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIndexName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIndexName());
      }
      if (hasTableName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTableName());
      }
      {
        int dataSize = 0;
        for (int element : getSelectFieldList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getSelectFieldList().size();
      }
      if (hasWhereStatement()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getWhereStatement());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.encyclo.messages.Search.SearchQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.Search.SearchQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.Search.SearchQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.Search.SearchQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.Search.SearchQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.Search.SearchQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.encyclo.messages.Search.SearchQuery prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.encyclo.messages.Search.SearchQuery result;
      
      // Construct using com.encyclo.messages.Search.SearchQuery.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.encyclo.messages.Search.SearchQuery();
        return builder;
      }
      
      protected com.encyclo.messages.Search.SearchQuery internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.encyclo.messages.Search.SearchQuery();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.encyclo.messages.Search.SearchQuery.getDescriptor();
      }
      
      public com.encyclo.messages.Search.SearchQuery getDefaultInstanceForType() {
        return com.encyclo.messages.Search.SearchQuery.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.encyclo.messages.Search.SearchQuery build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.encyclo.messages.Search.SearchQuery buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.encyclo.messages.Search.SearchQuery buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.selectField_ != java.util.Collections.EMPTY_LIST) {
          result.selectField_ =
            java.util.Collections.unmodifiableList(result.selectField_);
        }
        com.encyclo.messages.Search.SearchQuery returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.encyclo.messages.Search.SearchQuery) {
          return mergeFrom((com.encyclo.messages.Search.SearchQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.encyclo.messages.Search.SearchQuery other) {
        if (other == com.encyclo.messages.Search.SearchQuery.getDefaultInstance()) return this;
        if (other.hasIndexName()) {
          setIndexName(other.getIndexName());
        }
        if (other.hasTableName()) {
          setTableName(other.getTableName());
        }
        if (!other.selectField_.isEmpty()) {
          if (result.selectField_.isEmpty()) {
            result.selectField_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.selectField_.addAll(other.selectField_);
        }
        if (other.hasWhereStatement()) {
          mergeWhereStatement(other.getWhereStatement());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setIndexName(input.readString());
              break;
            }
            case 18: {
              setTableName(input.readString());
              break;
            }
            case 24: {
              addSelectField(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addSelectField(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              com.encyclo.messages.Search.SearchQuery.WhereStatement.Builder subBuilder = com.encyclo.messages.Search.SearchQuery.WhereStatement.newBuilder();
              if (hasWhereStatement()) {
                subBuilder.mergeFrom(getWhereStatement());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setWhereStatement(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional string index_name = 1;
      public boolean hasIndexName() {
        return result.hasIndexName();
      }
      public java.lang.String getIndexName() {
        return result.getIndexName();
      }
      public Builder setIndexName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIndexName = true;
        result.indexName_ = value;
        return this;
      }
      public Builder clearIndexName() {
        result.hasIndexName = false;
        result.indexName_ = getDefaultInstance().getIndexName();
        return this;
      }
      
      // optional string table_name = 2;
      public boolean hasTableName() {
        return result.hasTableName();
      }
      public java.lang.String getTableName() {
        return result.getTableName();
      }
      public Builder setTableName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTableName = true;
        result.tableName_ = value;
        return this;
      }
      public Builder clearTableName() {
        result.hasTableName = false;
        result.tableName_ = getDefaultInstance().getTableName();
        return this;
      }
      
      // repeated int32 select_field = 3;
      public java.util.List<java.lang.Integer> getSelectFieldList() {
        return java.util.Collections.unmodifiableList(result.selectField_);
      }
      public int getSelectFieldCount() {
        return result.getSelectFieldCount();
      }
      public int getSelectField(int index) {
        return result.getSelectField(index);
      }
      public Builder setSelectField(int index, int value) {
        result.selectField_.set(index, value);
        return this;
      }
      public Builder addSelectField(int value) {
        if (result.selectField_.isEmpty()) {
          result.selectField_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.selectField_.add(value);
        return this;
      }
      public Builder addAllSelectField(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.selectField_.isEmpty()) {
          result.selectField_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.selectField_);
        return this;
      }
      public Builder clearSelectField() {
        result.selectField_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .encyclo.SearchQuery.WhereStatement where_statement = 4;
      public boolean hasWhereStatement() {
        return result.hasWhereStatement();
      }
      public com.encyclo.messages.Search.SearchQuery.WhereStatement getWhereStatement() {
        return result.getWhereStatement();
      }
      public Builder setWhereStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasWhereStatement = true;
        result.whereStatement_ = value;
        return this;
      }
      public Builder setWhereStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement.Builder builderForValue) {
        result.hasWhereStatement = true;
        result.whereStatement_ = builderForValue.build();
        return this;
      }
      public Builder mergeWhereStatement(com.encyclo.messages.Search.SearchQuery.WhereStatement value) {
        if (result.hasWhereStatement() &&
            result.whereStatement_ != com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance()) {
          result.whereStatement_ =
            com.encyclo.messages.Search.SearchQuery.WhereStatement.newBuilder(result.whereStatement_).mergeFrom(value).buildPartial();
        } else {
          result.whereStatement_ = value;
        }
        result.hasWhereStatement = true;
        return this;
      }
      public Builder clearWhereStatement() {
        result.hasWhereStatement = false;
        result.whereStatement_ = com.encyclo.messages.Search.SearchQuery.WhereStatement.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:encyclo.SearchQuery)
    }
    
    static {
      defaultInstance = new SearchQuery(true);
      com.encyclo.messages.Search.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:encyclo.SearchQuery)
  }
  
  public static final class SearchResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse() {
      initFields();
    }
    private SearchResponse(boolean noInit) {}
    
    private static final SearchResponse defaultInstance;
    public static SearchResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.encyclo.messages.Search.internal_static_encyclo_SearchResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.encyclo.messages.Search.internal_static_encyclo_SearchResponse_fieldAccessorTable;
    }
    
    // repeated bytes response_message = 1;
    public static final int RESPONSE_MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> responseMessage_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getResponseMessageList() {
      return responseMessage_;
    }
    public int getResponseMessageCount() { return responseMessage_.size(); }
    public com.google.protobuf.ByteString getResponseMessage(int index) {
      return responseMessage_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.google.protobuf.ByteString element : getResponseMessageList()) {
        output.writeBytes(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getResponseMessageList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getResponseMessageList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.encyclo.messages.Search.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.Search.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.Search.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.encyclo.messages.Search.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.Search.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.encyclo.messages.Search.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.encyclo.messages.Search.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.encyclo.messages.Search.SearchResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.encyclo.messages.Search.SearchResponse result;
      
      // Construct using com.encyclo.messages.Search.SearchResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.encyclo.messages.Search.SearchResponse();
        return builder;
      }
      
      protected com.encyclo.messages.Search.SearchResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.encyclo.messages.Search.SearchResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.encyclo.messages.Search.SearchResponse.getDescriptor();
      }
      
      public com.encyclo.messages.Search.SearchResponse getDefaultInstanceForType() {
        return com.encyclo.messages.Search.SearchResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.encyclo.messages.Search.SearchResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.encyclo.messages.Search.SearchResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.encyclo.messages.Search.SearchResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.responseMessage_ != java.util.Collections.EMPTY_LIST) {
          result.responseMessage_ =
            java.util.Collections.unmodifiableList(result.responseMessage_);
        }
        com.encyclo.messages.Search.SearchResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.encyclo.messages.Search.SearchResponse) {
          return mergeFrom((com.encyclo.messages.Search.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.encyclo.messages.Search.SearchResponse other) {
        if (other == com.encyclo.messages.Search.SearchResponse.getDefaultInstance()) return this;
        if (!other.responseMessage_.isEmpty()) {
          if (result.responseMessage_.isEmpty()) {
            result.responseMessage_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.responseMessage_.addAll(other.responseMessage_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              addResponseMessage(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // repeated bytes response_message = 1;
      public java.util.List<com.google.protobuf.ByteString> getResponseMessageList() {
        return java.util.Collections.unmodifiableList(result.responseMessage_);
      }
      public int getResponseMessageCount() {
        return result.getResponseMessageCount();
      }
      public com.google.protobuf.ByteString getResponseMessage(int index) {
        return result.getResponseMessage(index);
      }
      public Builder setResponseMessage(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.responseMessage_.set(index, value);
        return this;
      }
      public Builder addResponseMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.responseMessage_.isEmpty()) {
          result.responseMessage_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.responseMessage_.add(value);
        return this;
      }
      public Builder addAllResponseMessage(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.responseMessage_.isEmpty()) {
          result.responseMessage_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.responseMessage_);
        return this;
      }
      public Builder clearResponseMessage() {
        result.responseMessage_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:encyclo.SearchResponse)
    }
    
    static {
      defaultInstance = new SearchResponse(true);
      com.encyclo.messages.Search.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:encyclo.SearchResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_encyclo_SearchQuery_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_encyclo_SearchQuery_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_encyclo_SearchQuery_WhereStatement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_encyclo_SearchQuery_WhereStatement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_encyclo_SearchQuery_WhereStatement_LogicalStatement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_encyclo_SearchQuery_WhereStatement_LogicalStatement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_encyclo_SearchResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_encyclo_SearchResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014search.proto\022\007encyclo\"\303\005\n\013SearchQuery\022" +
      "\022\n\nindex_name\030\001 \001(\t\022\022\n\ntable_name\030\002 \001(\t\022" +
      "\024\n\014select_field\030\003 \003(\005\022<\n\017where_statement" +
      "\030\004 \001(\0132#.encyclo.SearchQuery.WhereStatem" +
      "ent\032\267\004\n\016WhereStatement\022\r\n\005field\030\001 \001(\005\022>\n" +
      "\010operator\030\002 \001(\0162,.encyclo.SearchQuery.Wh" +
      "ereStatement.Operator\022\r\n\005value\030\003 \001(\t\022R\n\024" +
      "additional_statement\030\004 \003(\01324.encyclo.Sea" +
      "rchQuery.WhereStatement.LogicalStatement" +
      "\032\343\001\n\020LogicalStatement\022_\n\014logical_type\030\001 ",
      "\001(\0162I.encyclo.SearchQuery.WhereStatement" +
      ".LogicalStatement.LogicalStatementType\022<" +
      "\n\017where_statement\030\002 \001(\0132#.encyclo.Search" +
      "Query.WhereStatement\"0\n\024LogicalStatement" +
      "Type\022\006\n\002OR\020\000\022\007\n\003AND\020\001\022\007\n\003XOR\020\002\"\214\001\n\010Opera" +
      "tor\022\n\n\006EQUALS\020\000\022\013\n\007GREATER\020\001\022\013\n\007SMALLER\020" +
      "\002\022\025\n\021GREATER_OR_EQUALS\020\003\022\025\n\021SMALLER_OR_E" +
      "QUALS\020\004\022\016\n\nNOT_EQUALS\020\005\022\013\n\007IS_NULL\020\006\022\017\n\013" +
      "IS_NOT_NULL\020\007\"*\n\016SearchResponse\022\030\n\020respo" +
      "nse_message\030\001 \003(\014B\036\n\024com.encyclo.message",
      "sB\006Search"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_encyclo_SearchQuery_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_encyclo_SearchQuery_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_encyclo_SearchQuery_descriptor,
              new java.lang.String[] { "IndexName", "TableName", "SelectField", "WhereStatement", },
              com.encyclo.messages.Search.SearchQuery.class,
              com.encyclo.messages.Search.SearchQuery.Builder.class);
          internal_static_encyclo_SearchQuery_WhereStatement_descriptor =
            internal_static_encyclo_SearchQuery_descriptor.getNestedTypes().get(0);
          internal_static_encyclo_SearchQuery_WhereStatement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_encyclo_SearchQuery_WhereStatement_descriptor,
              new java.lang.String[] { "Field", "Operator", "Value", "AdditionalStatement", },
              com.encyclo.messages.Search.SearchQuery.WhereStatement.class,
              com.encyclo.messages.Search.SearchQuery.WhereStatement.Builder.class);
          internal_static_encyclo_SearchQuery_WhereStatement_LogicalStatement_descriptor =
            internal_static_encyclo_SearchQuery_WhereStatement_descriptor.getNestedTypes().get(0);
          internal_static_encyclo_SearchQuery_WhereStatement_LogicalStatement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_encyclo_SearchQuery_WhereStatement_LogicalStatement_descriptor,
              new java.lang.String[] { "LogicalType", "WhereStatement", },
              com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.class,
              com.encyclo.messages.Search.SearchQuery.WhereStatement.LogicalStatement.Builder.class);
          internal_static_encyclo_SearchResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_encyclo_SearchResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_encyclo_SearchResponse_descriptor,
              new java.lang.String[] { "ResponseMessage", },
              com.encyclo.messages.Search.SearchResponse.class,
              com.encyclo.messages.Search.SearchResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
